# SciPy

SciPy представляет собой совокупность математических алгоритмов и функций, построенных как расширение Numpy на Python. Он значительно расширяет возможности интерактивной сессии Python, предоставляя пользователю команды высокого уровня и классы для управления и визуализации данных. Со SciPy интерактивный сеанс Python становится средой обработки данных и системой прототипирования соперничающей с такими системами, как MATLAB, IDL, Octave, R-Lab, and SciLab.

*Модули SciPy*:

* constants - Физические константы и коэффициенты пересчёта

* cluster - Векторное квантование

* fftpack - Дискретные алгоритмы преобразования Фурье

* integrate - Инструменты для интегрирования

* interpolate - Инструменты для интерполяции

* io - Ввод-вывод данных

* lib - Работа со сторонними библиотеками

* linalg - Линейная алгебра

* optimize - Средства оптимизации

* sandbox - Экспериментальный код

* signal - Обработка сигналов

* sparse - Поддержка разреженных матриц

* special - Специальные функции

* stats - Статистические функции

* weave - Использование кода, написанного на языках C и C++

In [18]:
# подключим необходимые в дальнейшем модули
import numpy as np


## Подмодуль linalg

Модуль linalg предназначен для реализации линейной алгебры.

In [19]:
from scipy import linalg

**Метод dot(a,b)**

Матричное умножение a × b.


In [20]:
A = np.array([[ 1., 1., 1., 1.], [ 1., 1., 1., 1.], [ 1., 1., 1., 1.],[ 1., 1., 1., 1.]])
print('A:')
print(A)
B = np.array([[ 1., 1.], [ 1., 1.], [ 1., 1.], [ 1., 1.]])
print('B:')
print(B)

q = np.dot(A, B)
print(q)

A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
B:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


**Метод solve(a,b)**

Задача: нужно найти такой x, что, если матрицу a умножить на x, то получится матрица b.

In [21]:
a = np.array([[3, 2, 0],[1, -1, 0],[0, 5, 1]])
print('a:')
print(a)
b = np.array([2, 4, -1])
print('b:')
print(b)
x = linalg.solve(a,b)
print('x =',x)

a:
[[ 3  2  0]
 [ 1 -1  0]
 [ 0  5  1]]
b:
[ 2  4 -1]
x = [ 2. -2.  9.]


In [22]:
np.dot(a, x) # Проверим - результат должен быть равен b

array([ 2.,  4., -1.])

**Метод det(m)**

Нахождение определителя матрицы.

In [23]:
B = np.array([[-4, -1, 2], [10, 4, -1], [8, 3, 1]])
print(B)
q = np.linalg.det(B)
print(q)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
-14.000000000000009


**Метод svd(x)**

Сингулярное разложение матрицы.

In [24]:
x = np.random.randn(4, 3)
print('x:')
print(x)
U, D, V = linalg.svd(x)
print (U.shape, D.shape, V.shape)
print (type(U), type (D), type(V))

x:
[[ 0.72286492  1.42671762 -1.0279148 ]
 [ 0.12013789  0.31484895 -0.0222108 ]
 [-2.70336197  0.14033103  1.09409649]
 [ 0.87111726  2.62341721 -1.38875189]]
(4, 4) (3,) (3, 3)
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


## Подмодуль optimize

In [25]:
from scipy import optimize # подмодуль optimize

В модуле optimize есть **метод minimize**, которому достаточно передать функцию, передать начальное приближение. Мы видим, что значение функции равно примерно 2 в точке с  координатами x: array([-1.03529084e-07,  4.99997747e+00]), которые с достаточно высокой степенью точности совпадают с правильными.

In [26]:
def f(x):
    return 3**(x[0]**2) + 3**(1e-8*x[1]**2)

x_min = optimize.minimize(f, [-5, 5])
print(x_min)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.000000274650515
        x: [-9.262e-08  5.000e+00]
      nit: 36
      jac: [-1.788e-07  8.941e-08]
 hess_inv: [[ 4.550e-01 -1.001e-05]
            [-1.001e-05  1.000e+00]]
     nfev: 123
     njev: 41


Если нужна только точка минимума, можно обратится к полю X нужного объекта

In [27]:
print(x_min.x)

[-9.26211389e-08  4.99997630e+00]


## Подмодуль integrate

In [28]:
import scipy.integrate as integrate # подмодуль integrate

**Функция quad** предназначена для интегрирования функции одной переменной между двумя точками.
Точки могут быть (inf), чтобы указать бесконечные пределы. Например, предположим, что вы хотите интегрировать функцию
Бесселя jv (2.5, x) вдоль интервала [0,4.5]

In [29]:
import scipy.special as special
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print(result)


(1.1178179380783253, 7.866317216380692e-09)


**Метод root**

В следующем примере рассматривается трансцендентное уравнение с одной переменной
x * x + 2cos (x) = 0.

Корень уравнения можно найти следующим образом.

In [30]:
from scipy.optimize import root
def func(x):
    return x*2 + 2 * np.cos(x)
sol = root(func, 0.3)
print(sol)

 message: The solution converged.
 success: True
  status: 1
     fun: [ 2.220e-16]
       x: [-7.391e-01]
  method: hybr
    nfev: 12
    fjac: [[-1.000e+00]]
       r: [-3.347e+00]
     qtf: [-2.777e-12]


## sparse - Поддержка разреженных матриц

Работа с большими разреженными матрицами в Python: десятки миллионов элементов = 10^4 x 10^4. Пример - исходная матрица не помещается в ОЗУ:

https://docs.scipy.org/doc/scipy/reference/sparse.html


In [31]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand

In [32]:
n = 1000

Создадим матрицу 1000x1000 lil_matrix (lil = list of lists):

In [33]:
A = lil_matrix((n, n))
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]
A.setdiag(rand(n))

Преобразуем ее к формату CSR и решим A*x = b:

In [34]:
A = A.tocsr()
b = rand(n)
print(len(b))
x = spsolve(A, b)

1000


Преобразуем матрицу к неразреженной, решим, и проверим, что результаты совпадают:

In [35]:
x_ = solve(A.toarray(), b)

Теперь вычислим норму ошибки (ответы почти не отличаются):

In [36]:
err = norm(x-x_)
err < 1e-10

np.True_

In [37]:
from scipy.sparse import rand
import numpy
from datetime import datetime

In [38]:
n = 10000
A = rand(n, n, density=0.25, format="csr")
b = numpy.random.rand(n)

In [39]:
len(b)

10000

In [40]:
type(b)

numpy.ndarray

In [41]:
A[3,0]

np.float64(0.0)

In [42]:
type(A)

scipy.sparse._csr.csr_matrix

In [43]:
A.shape

(10000, 10000)

In [44]:
import sys

sys.getsizeof(A)

56

In [45]:
sys.getsizeof(b)

80112

In [46]:
start_time = datetime.now()
x = spsolve(A, b)
print(datetime.now() - start_time)

0:01:25.480131


In [47]:
A = A.toarray()

In [48]:
sys.getsizeof(A)

800000128

In [49]:
start_time = datetime.now()
x_ = solve(A, b)
print(datetime.now() - start_time)

0:00:27.585467


In [50]:
err = norm(x-x_)
err < 1e-8

np.True_

In [51]:
n = 20000
A = rand(n, n, density=0.25, format="csr")

In [52]:
b = numpy.random.rand(n)

In [53]:
sys.getsizeof(A)

56

In [54]:
A = A.toarray()

In [55]:
sys.getsizeof(A)

3200000128

In [56]:
sys.getsizeof(1111111111111111134)

32

In [57]:
x=3
id(x)

10750920

In [58]:
y=3
id(y)

10750920

In [59]:
x=5
id(x)

10750984

In [60]:
v=1+4
id(v)

10750984

In [61]:
x=256
id(x)

10759016

In [62]:
y=256
id(y)

10759016

In [63]:
x=-5
print(id(x))
y=-5
print(id(y))

10750664
10750664


In [64]:
x=257
print(id(x))
y=257
print(id(y))

134752723009744
134752723010480


In [65]:
x=-6
print(id(x))
y=-6
print(id(y))

134752723023664
134752723022608


In [66]:
id(-5)

10750664